export interface Empleado{
    emdid?: number;
    emdcedula?: string,
    emdnombres?: string,
    emdapellidos?: string,
    emdsexo?:string,
    emdzona?:string,
    emdfecnacido?: Date,
    emdestcivil?: string,
    emdnivelestudio?: string,
    emdprofesion?: string,
    emddepartamento?:string,
    emdciudad?: string,
    emddireccion?: string,
    emdtelefono?: string,
    emdemail?: string,
    emdestracto?: string,
    emdtipovivienda?: string,
    emdpersdepen?: number,
    emdempresa?: number,
    emdtiempolab?: string,
    emdcargo?: string,
    emdtipodecargo?: string,
    emdtiemcargo?: string,
    emdarea?: number,
    emdtipocontrato?: string,
    emdhorasdia?:string,
    emdtiposalario?: string,
    emdusuarioreg?: string,
    emdipreg?: string
    nomempresa?:string,
    ciudadEmpresa?:string,
    DepartamentoEmpresa?:string,
    emdactivo?:string
    emdfecnacidoRepor?: Number,
    areaNom?: string,
    emdtraciudad?:string,
    emdtradepartamento?:string

}