export interface Estres{
    estid? : number,
    estidempleado? : number,
    estdolorcuello? : string,
    estprobgastrico? : string,
    estprobrespira? : string,
    estdolorcabeza? : string,
    esttrastsueno? : string,
    estpalpitacion? : string,
    estcamapetito? : string,
    estprobgenital? : string,
    estdiffamiliar? : string,
    estdifquieto? : string,
    estdifpersonas? : string,
    estsensaislami? : string,
    estsobrecarga? : string,
    estdifconcentrar? : string,
    estaumentaccid? : string,
    estsentfrustra? : string,
    estcansancio? : string,
    estdismrendimie? : string,
    estdeseonotrab? : string,
    estpocointeres? : string,
    estdifdecisiones? : string,
    estcambioempleo? : string,
    estsentisoledad? : string,
    estsentinegativo? : string,
    estsetangpretris?:string,
    estconsdrogas? : string,
    estsentinosirve? : string,
    estconsucigarri? : string,
    estperdirazon? : string,
    estcomprigido? : string,
    estsensproblem? : string,
    estfechareg? : Date,
    estfechamod? : Date,
    estusuarioreg? : string
}


