export interface Extralaboral{
    extid? : number,
    extidempleado? : number,
    extfaciltransporte? :string,
    extvariostransporte? :string,
    extmuchotiemviaje? :string,
    exttranscomodo? :string,
    extzonasegura? :string,
    extzonadelincuencia? :string,
    extfacilcmedico? :string,
    extbuenasvias? :string,
    extcercatransporte? :string,
    extcondicvivienda? :string,
    extagualuz? :string,
    extpermdescanzar? :string,
    extviviendacomoda? :string,
    exttiemporecreo? :string,
    exttiempodescanzo? :string,
    exttiempopersonal? :string,
    exttiempofamilia? :string,
    extbuenacomunica? :string,
    extrelacionamigos? :string,
    extconversoperson? :string,
    extamigosescuchan? :string,
    extapoyofamiliar? :string,
    exthabloconperso? :string,
    extproblemfamiliar? :string,
    extrelacionfamiliar? :string,
    extquitanenergia? :string,
    extresolveamistosa? :string,
    extafectrelacionestra? :string,
    extdineroalcanza? :string,
    extpresupuesfamilia? :string,
    extdeudashogar? :string,
    extfechareg? :Date,
    extfechamod? :Date,
    extusuarioreg? : string 
}
