export interface ValorFisico{
    vafid?: number,
    vafidempresa?:number ,
    vafidarea?:number ,
    vafidnombre?:string ,
    vafsede?:string ,
    vafpeso?:number ,
    vaftalla?:number ,
    vafimc?:number ,
    vafperimetro?:number ,
    vafp0?:number ,
    vafp1?:number ,
    vafp2?:number ,
    vaftestbiering?:number ,
    vaftestpuenteder?:number ,
    vaftestpuenteizq?:number ,
    vaftestresistronco?:number ,
    vaftestflextronco?:number ,
    vaftestmovhombder?:number ,
    vaftestmovhombizq?:number ,
    vaftestmovartichomb?:number ,
    vafcedula?:number,
    vafsexo?:string,
    vafgruposanguineo?:string,
    vaftelefono?:string,
    vafciudad?:string,
    vafedad?:string,
    vafcorreo?:string,
    vafcargo?:string,
    vaffecha?:Date,
    vafcs01?:number,
    vafcs02?:number,
    vafcs03?:number,
    vafcs04?:number,
    vafcs05?:number,
    vafcs06?:number,
    vafcs07?:number,
    vafcs08?:number,
    vafcs09?:number,
    vafcs10?:number,
    vafcs11?:number,
    vafcs12?:number,
    vafcs13?:number,
    vafcs14?:number,
    vafcs15?:string,
    vafcs16?:number,
    vafcs17?:number,
    vafcs18?:number,
    vafcs19?:number,
    vafcs20?:number,
    vafcs21?:string
    vafcancer_opc?:number,
    vafcancer_var?:any,
    vafhiper_arte_opc?:number,
    vafhiper_arte_var?:any,
    vafasma_opc?:number,
    vafasma_var?:any,
    vafcardio_opc?:number,
    vafcardio_var?:any,
    vafdiabet_opc?:number,
    vafdiabet_var?:any,
    vafalergia_opc?:number,
    vafalergia_var?:any,
    vafartritis_opc?:number,
    vafartritis_var?:any,
    vafem_opc?:number,
    vafem_var?:any,
    vafer_opc?:number,
    vafer_var?:any,
    vafmujer40_opc?:number,
    vafmujer40_var?:string,
    vafhombre40_opc?:number,
    vafhombre40_var?:string,
    vafdiscapacidad_opc?:number,
    vafdiscapacidad_var?:string,
    vaf_familiap01_opc?:number,
    vaf_familiap02_opc?:number,
    vaf_familia_num?:number,
    vaf_actifisip01_opc?:number,
    vaf_actifisip02_opc?:number,
    vaf_actifisi_num?:number,
    vaf_nutricionp01_opc?:number,
    vaf_nutricionp02_opc?:number,
    vaf_nutricionp03_opc?:number,
    vaf_nutricionp03_var?:string,
    vaf_tabacop01_opc?:number,
    vaf_tabacop02_opc?:number,
    vaf_tabacop02_var?:string,
    vaf_alcoholp01_opc?:number,
    vaf_alcoholp02_opc?:number,
    vaf_alcoholp03_opc?:number,
    vaf_suenop01_opc?:number,
    vaf_suenop02_opc?:number,
    vaf_suenop03_opc?:number,
    vaf_tipop01_opc?:number,
    vaf_tipop02_opc?:number,
    vaf_introspep01_opc?:number,
    vaf_introspep02_opc?:number,
    vaf_introspep03_opc?:number,
    vaf_condup01_opc?:number,
    vaf_condup02_opc?:number,
    vaf_otrasdp01_opc?:number,
    vaf_otrasdp02_opc?:number,
    vaf_otrasdp03_opc?:number,
    vaf_nutricion_num?:number,
    vaf_tabaco_num?:number,
    vaf_alcohol_num?:number,
    vaf_sueno_num?:number,
    vaf_tipo_num?:number,
    vaf_introspe_num?:number,
    vaf_condu_num?:number,
    vaf_otrasd_num?:number,
    vaf_fantastico_total?:number,
    vafAF_p01?:number,
    vafAF_p02?:number
}