export interface ValorFisico{
    vafid?: number,
    vafidempresa?:number ,
    vafidarea?:number ,
    vafidnombre?:string ,
    vafsede?:string ,
    vafpeso?:number ,
    vaftalla?:number ,
    vafimc?:number ,
    vafperimetro?:number ,
    vafp0?:number ,
    vafp1?:number ,
    vafp2?:number ,
    vaftestbiering?:number ,
    vaftestpuenteder?:number ,
    vaftestpuenteizq?:number ,
    vaftestresistronco?:number ,
    vaftestflextronco?:number ,
    vaftestmovhombder?:number ,
    vaftestmovhombizq?:number ,
    vaftestmovartichomb?:number ,
    vafobservaciones?:string ,
    vafcedula?:number ,  
}