export interface ValorFisico{
    vafid?: number,
    vafidempresa?:number ,
    vafidarea?:number ,
    vafidnombre?:string ,
    vafsede?:string ,
    vafpeso?:number ,
    vaftalla?:number ,
    vafimc?:number ,
    vafperimetro?:number ,
    vafp0?:number ,
    vafp1?:number ,
    vafp2?:number ,
    vaftestbiering?:number ,
    vaftestpuenteder?:number ,
    vaftestpuenteizq?:number ,
    vaftestresistronco?:number ,
    vaftestflextronco?:number ,
    vaftestmovhombder?:number ,
    vaftestmovhombizq?:number ,
    vaftestmovartichomb?:number ,
    vafcedula?:number,
    vafsexo?:string,
    asigSexo?:string,
    vafgruposanguineo?:string,
    vaftelefono?:string,
    vafciudad?:string,
    vafedad?:string,
    vafcorreo?:string,
    vafcargo?:string,
    vaffecha?:Date,
    vafcs01?:number,
    pcs01?:string,
    vafcs02?:number,
    pcs02?:string,
    vafcs03?:number,
    pcs03?:string,
    vafcs04?:number,
    pcs04?:string,
    vafcs05?:number,
    pcs05?:string,
    vafcs06?:number,
    pcs06?:string,
    vafcs07?:number,
    pcs07?:string,
    vafcs08?:number,
    pcs08?:string,
    vafcs09?:number,
    pcs09?:string,
    vafcs10?:number,
    pcs10?:string,
    vafcs11?:number,
    pcs11?:string,
    vafcs12?:number,
    pcs12?:string,
    vafcs13?:number,
    pcs13?:string,
    vafcs14?:number,
    pcs14?:string,
    vafcs15?:string,
    vafcs16?:number,
    pcs16?:string,
    vafcs17?:number,
    pcs17?:string,
    vafcs18?:number,
    pcs18?:string,
    vafcs19?:number,
    pcs19?:string,
    vafcs20?:number,
    pcs20?:string,
    vafcs21?:string
    vafcancer_opc?:number,
    pcancer_opc?:string,
    vafcancer_var?:any,
    vafhiper_arte_opc?:number,
    phiper_arte_opc?:string,
    vafhiper_arte_var?:any,
    vafasma_opc?:number,
    pasma_opc?:string,
    vafasma_var?:any,
    vafcardio_opc?:number,
    pcardio_opc?:string,
    vafcardio_var?:any,
    vafdiabet_opc?:number,
    pdiabet_opc?:string,
    vafdiabet_var?:any,
    vafalergia_opc?:number,
    palergia_opc?:string,
    vafalergia_var?:any,
    vafartritis_opc?:number,
    partritis_opc?:string,
    vafartritis_var?:any,
    vafem_opc?:number,
    pem_opc?:string,
    vafem_var?:any,
    vafer_opc?:number,
    per_opc?:string,
    vafer_var?:any,
    vafmujer40_opc?:number,
    pmujer40_opc?:string,
    vafmujer40_var?:string,
    pmujer40_var?:string,
    vafhombre40_opc?:number,
    phombre40_opc?:string,
    vafhombre40_var?:string,
    phombre40_var?:string,
    vafdiscapacidad_opc?:number,
    pdiscapacidad_opc?:string,
    vafdiscapacidad_var?:string,
    vaf_familiap01_opc?:number,
    pfamiliap01_opc?:string,
    vaf_familiap02_opc?:number,
    pfamiliap02_opc?:string,
    vaf_familia_num?:number,
    vaf_actifisip01_opc?:number,
    pactifisip01_opc?:string,
    vaf_actifisip02_opc?:number,
    pactifisip02_opc?:string,
    vaf_actifisi_num?:number,
    vaf_nutricionp01_opc?:number,
    pnutricionp01_opc?:string,
    vaf_nutricionp02_opc?:number,
    pnutricionp02_opc?:string,
    vaf_nutricionp03_opc?:number,
    pnutricionp03_opc?:string,
    vaf_nutricionp03_var?:string,
    vaf_tabacop01_opc?:number,
    ptabacop01_opc?:string,
    vaf_tabacop02_opc?:number,
    ptabacop02_opc?:string,
    vaf_tabacop02_var?:string,
    vaf_alcoholp01_opc?:number,
    palcoholp01_opc?:string,
    vaf_alcoholp02_opc?:number,
    palcoholp02_opc?:string,
    vaf_alcoholp03_opc?:number,
    palcoholp03_opc?:string,
    vaf_suenop01_opc?:number,
    psuenop01_opc?:string,
    vaf_suenop02_opc?:number,
    psuenop02_opc?:string,
    vaf_suenop03_opc?:number,
    psuenop03_opc?:string,
    vaf_tipop01_opc?:number,
    vaf_tipop02_opc?:number,
    ptipop01_opc?:string,
    ptipop02_opc?:string,
    vaf_introspep01_opc?:number,
    vaf_introspep02_opc?:number,
    vaf_introspep03_opc?:number,
    pintrospep01_opc?:string,
    pintrospep02_opc?:string,
    pintrospep03_opc?:string,
    vaf_condup01_opc?:number,
    vaf_condup02_opc?:number,
    pcondup01_opc?:string,
    pcondup02_opc?:string,
    vaf_otrasdp01_opc?:number,
    vaf_otrasdp02_opc?:number,
    vaf_otrasdp03_opc?:number,
    potrasdp01_opc?:string,
    potrasdp02_opc?:string,
    potrasdp03_opc?:string,
    vaf_nutricion_num?:number,
    vaf_tabaco_num?:number,
    vaf_alcohol_num?:number,
    vaf_sueno_num?:number,
    vaf_tipo_num?:number,
    vaf_introspe_num?:number,
    vaf_condu_num?:number,
    vaf_otrasd_num?:number,
    vaf_fantastico_total?:number,
    vafAF_p01?:number,
    pAF_p01?:string,
    vafAF_p02?:number,
    pAF_p02?:string,
    vaf_fecha_creacion?:Date,
    nombreEmp?:string,
    nombreArea?:string,
}